update install-ssh-key to know about new key names.

diff --git a/bin/install-ssh-key b/bin/install-ssh-key
--- a/bin/install-ssh-key
+++ b/bin/install-ssh-key
@@ -4,7 +4,14 @@ set -e
 if [ -z "$1" ] ; then echo "Usage: $0 <user@host>" ; exit 1; fi
 
 set -u
+
+user="$USER"
+hostname="$(hostname -s)"
+file="$(ls -1 "$HOME/.ssh/$user@$hostname."*".pub")"
+if ! [ -e "$file" ] ; then echo "Public key not found: $file" ; exit 1 ; fi
+echo "Public key: $file"
+
 TGT="$1"
 echo "Target: ${TGT}"
 
-cat "$HOME/.ssh/id_rsa.pub" | ssh "${TGT}" 'cd ; echo -n "configuring ssh keys... " && mkdir -p .ssh && chmod 700 .ssh && touch .ssh/authorized_keys && cat - >> .ssh/authorized_keys && chmod 600 .ssh/authorized_keys && echo "done."'
+cat "$file" | ssh "${TGT}" 'cd ; echo -n "configuring ssh keys... " && mkdir -p .ssh && chmod 700 .ssh && touch .ssh/authorized_keys && cat - >> .ssh/authorized_keys && chmod 600 .ssh/authorized_keys && echo "done."'
